#tp_log("Homing")
#x1, sol = current_pos = get_current_posx(ref=DR_WORLD)
#tp_log("Current Pos: " + str(x1))
#
#dist1 = get_distance(x1, System_grinder_top)
#dist2 = get_distance(x1, fkin(System_init_j))
#dist3 = get_distance(x1, System_blades_top)
#
#if dist1 < dist2:
    #movel(System_grinder_top, 50, 20)
#elif dist3 < dist2:
    #movel(System_blades_top, 50, 20)
    #
#movej(System_init_j, 100, 20)

REG_CALIBRATION = 142
set_modbus_slave(REG_CALIBRATION,0)
set_tcp("Tool_v1")
wait(2)
depth_offset = posx(20, 0, 0, 0, 0, 0)
current_pose = get_current_posx()[0]

new_tcp = trans(current_pose, depth_offset, DR_TOOL, DR_BASE)

ucs_id = set_user_cart_coord(new_tcp, ref=DR_BASE) # apparently sets tcp
current_pose2 = get_current_posx(ref=ucs_id)[0]
tp_log(str(current_pose2))
movel(posx(0,0,0,0,90,0), time=5, ref=ucs_id)   # rotate about pivot

#set_tcp("Flange")