set_tcp("Flange")
#tp_log("Homing")
#x1, sol = current_pos = get_current_posx(ref=DR_WORLD)
#tp_log("Current Pos: " + str(x1))
#
#dist1 = get_distance(x1, System_grinder_top)
#dist2 = get_distance(x1, fkin(System_init_j))
#dist3 = get_distance(x1, System_blades_top)
#
#if dist1 < dist2:
    #movel(System_grinder_top, 50, 20)
#elif dist3 < dist2:
    #movel(System_blades_top, 50, 20)
    #
    
#set_tcp("Flange")
##movej(System_init_j, 20, 20)
##
##movel(System_grinder_top, 50, 20)
#
#movel(System_grinder_app, 50, 20)
#
#movel(System_grinder_invert, 20, 20)


#set_tcp("Tool_v1")
#wait(2)
#depth_offset = posx(20, 0, 0, 0, 0, 0)
#current_pose = get_current_posx()[0]
#
#new_tcp = trans(current_pose, depth_offset, DR_TOOL, DR_BASE)
#
#ucs_id = set_user_cart_coord(new_tcp, ref=DR_BASE) # apparently sets tcp
#current_pose2 = get_current_posx(ref=ucs_id)[0]
#tp_log(str(current_pose2))
#movel(posx(0,0,0,0,90,0), time=5, ref=ucs_id)   # rotate about pivot

#set_tcp("Flange")

#set_tcp("Tool_v1")
#
#def on_arc(base, pivot, transformation):
    ## pivot: [px, py, pz] offset in tool frame
    ## transformation: posx whose orientation is the rotation to apply about pivot
    #px, py, pz = pivot[0], pivot[1], pivot[2]
    #rz1, ry, rz2 = transformation[3]/2, transformation[4]/2, transformation[5]/2
    #rz11, ry1, rz21 = transformation[3], transformation[4], transformation[5]
#
    #R = eul2rotm([rz1, ry, rz2])
    #tx = px - (R[0][0]*px + R[0][1]*py + R[0][2]*pz)
    #ty = py - (R[1][0]*px + R[1][1]*py + R[1][2]*pz)
    #tz = pz - (R[2][0]*px + R[2][1]*py + R[2][2]*pz)
    #delta = posx(tx, ty, tz, rz1, ry, rz2)
    #mid = trans(base, delta, DR_TOOL, DR_BASE)
    #
    #R1 = eul2rotm([rz11, ry1, rz21])
    #tx1 = px - (R1[0][0]*px + R1[0][1]*py + R1[0][2]*pz)
    #ty1 = py - (R1[1][0]*px + R1[1][1]*py + R1[1][2]*pz)
    #tz1 = pz - (R1[2][0]*px + R1[2][1]*py + R1[2][2]*pz)
    #delta1 = posx(tx1, ty1, tz1, rz11, ry1, rz21)
    #end = trans(base, delta1, DR_TOOL, DR_BASE)
    #
    #return mid, end
#
#start = get_current_posx()[0]
#pivot = [20, 0, 0] 
#
#mid, end = on_arc(start, pivot, posx(0, 0, 0, 0, -5, 0))

#movec(mid, end, time=10, ref=DR_BASE)

# Bottom
#posj(-270.24, 37.41, 109.48, -0.23, -41.1, 134.99)

# Top
#posj(-270.22, 28.33, 97.08, -0.04, 28.05, 134.9)

#posx(0, 599.74, 177.78, 90, 160, -180)

loading_val = True

tp_log("Magnets On")
set_mode_analog_output(ch=1, mod=DR_ANALOG_VOLTAGE)
set_analog_output(ch=1, val=3.3)

if (loading_val):
    tp_log("Loading")
    x1, sol = current_pos = get_current_posx(ref=DR_WORLD)
    tp_log("Current Pos: " + str(x1))
    
    local_zones = [System_grinder_top,fkin(System_init_j), System_blades_top, System_grinder2_top]
    dist = [0] * 4
    #dist1 = get_distance(x1, System_grinder_top)
    #dist2 = get_distance(x1, fkin(System_init_j))
    #dist3 = get_distance(x1, System_blades_top)
    #dist4 = get_distance(x1, System_grinder2_top)
    
    for i in range(0,len(local_zones)):
        dist[i] = get_distance(x1, local_zones[i])
    
    closest_zone = dist.index(min(dist))
    
    while closest_zone != 1:
        tp_log("Closest_zone: " + str(closest_zone))
        if closest_zone == 0:
            movel(local_zones[0], 100, 20)
            closest_zone += 1
        elif closest_zone == 2:
            movel(local_zones[2], 100, 20)
            closest_zone -= 1
        elif closest_zone == 3:
            movel(local_zones[3], 100, 20)
            closest_zone -= 1
            
    tp_log("Going to init now")        
    movej(System_init_j, time=5) 
    
    wait(5)
    movel(System_grinder_top, 50, 20)
    
else:
    tp_log("Skipped Loading")
       

REG_GRIND_READY = 138 # For camera
set_modbus_slave(REG_GRIND_READY,1)
wait(5)

#movel(System_grinder_top, 50, 20)
movel(System_grinder_app, 50, 20)


set_tcp("Flange")
REG_CALIBRATION = 141
REG_CALIBRATION_ANGLE = 142

set_modbus_slave(REG_CALIBRATION, 0)

movel(System_angle_inspection, 20, 20)

inspection_depth = posx(System_angle_inspection)
#41
inspection_depth[1] = (inspection_depth[1] + 39) - blade_depth
tp_log("New Y: " + str(inspection_depth))

movel(inspection_depth, 20, 20)

# STARTING INSPECTION
set_tcp("Tool_v1")

def rotation(base, pivot, transformation):
    # pivot: [px, py, pz] offset in tool frame
    # transformation: posx whose orientation is the rotation to apply about pivot
    px, py, pz = pivot[0], pivot[1], pivot[2]
    rz1, ry, rz2 = transformation[3], transformation[4], transformation[5]

    R = eul2rotm([rz1, ry, rz2])
    tx = px - (R[0][0]*px + R[0][1]*py + R[0][2]*pz)
    ty = py - (R[1][0]*px + R[1][1]*py + R[1][2]*pz)
    tz = pz - (R[2][0]*px + R[2][1]*py + R[2][2]*pz)
    delta = posx(tx, ty, tz, rz1, ry, rz2)
    final = trans(base, delta, DR_TOOL, DR_BASE)
    
    return final

current_angle = 70

set_modbus_slave(REG_CALIBRATION, 1)
set_modbus_slave(REG_CALIBRATION_ANGLE, 70 * 10)
    
for i in range(0,60,5):
    current_rot = get_current_posx()[0]
    pivot = [blade_depth,0,0]
    transformation = posx(0, 0, 0, 0, 5, 0)
    new_rot = rotation(current_rot, pivot, transformation)
    movel(new_rot, time=2, ref=DR_BASE)
    current_angle = current_angle - 5
    tp_log("Current angle: " + str(current_angle))
    set_modbus_slave(REG_CALIBRATION_ANGLE, current_angle * 10)
    wait(1)
    
       
set_tcp("Flange")

movel(System_angle_inspection, 20, 20)
movel(System_grinder_app, 50, 20)
tp_log("Current pos: " + str(get_current_posx()[0]))

set_modbus_slave(REG_CALIBRATION, 0)

tp_log("Calibration finished")

#posx(-0.01, 603.89, 151.36, 90, 120, -180)


    

    