# Modbus Register Addresses
REG_BAY_ID = 128
REG_GRINDER_ID = 129
REG_ANGLE = 130
REG_DEPTH = 131
REG_LENGTH = 132
REG_CONFIG_VERSION = 133

REG_DETECTION_X = 134
REG_DETECTION_Y = 135
REG_STATUS = 136
REG_START = 138 
REG_COMMAND = 137

# Command codes
CMD_READ_DETECTION = 11
CMD_RESET = 22
while(1):
    if (get_modbus_slave(REG_START) == 1):
        tp_log("Start command received")
        x1, sol = current_pos = get_current_posx(ref=DR_WORLD)
        tp_log("Current Pos: " + str(x1))
        
        dist1 = get_distance(x1, System_grinder_top)
        dist2 = get_distance(x1, fkin(System_init_j))
        dist3 = get_distance(x1, System_blades_top)
        
        if dist1 < dist2:
            movel(System_grinder_top, 20, 20)
        elif dist3 < dist2:
            movel(System_blades_top, 20, 20)
        
        movel(System_blades_top, 20, 20)
        movel(System_blade1_new, 20, 20)
        set_ref_coord(DR_TOOL)
        
        movel(posx(0, 0, 11, 0, 0, 0), v=50, a=100)
        movel(posx(0, 9, 0, 0, 0, 0), v=10, a=10)
        movel(posx(0, 0, 1, 0, 0, 0), v=10, a=10)
        set_mode_analog_output(ch=1, mod=DR_ANALOG_VOLTAGE)
#
        set_analog_output(ch=1, val=3.3)
        movel(posx(0, -9, 0, 0, 0, 0), v=10, a=10)
        movel(posx(0, 0, -11, 0, 0, 0), v=50, a=100)
        
        set_ref_coord(DR_BASE)
        #Turn on magnets
        movel(System_blades_top, 100, 20)
        movel(IR_sensor, 50, 20)
        
        set_digital_output(1, ON)
        
        amovel(posx(0,500,0,0,0,0), vel=30, acc=10,mod=DR_MV_MOD_REL)
        while (get_digital_input(1) == 0):
            wait(0.005)
        stop(DR_SSTOP)
        
        blade_left, sol = get_current_posx(ref=DR_WORLD)
        
        movel(posx(0,-30,0,0,0,0), vel=40, acc=10,mod=DR_MV_MOD_REL)
        
        amovel(posx(0,-400,0,0,0,0), vel=30, acc=10,mod=DR_MV_MOD_REL)
        
        while (get_digital_input(1) == 0):
            wait(0.005)
        
        stop(DR_SSTOP)
        blade_right, sol = get_current_posx(ref=DR_WORLD)
        
        blade_l = blade_left[1] - blade_right[1] - 10
        if (blade_l<260):
            set_analog_output(ch=1, val=1.2)
        elif (blade_1<520):
            set_analog_output(ch=1, val=2.2)
        else:
            set_analog_output(ch=1, val=3.2)
        
        movej(System_init_j, 20, 20)
        movel(System_grinder_top, 20, 20)
        movel(System_grinder_app, 20, 20)
        movel(System_grinder_invert, 20, 20)
        
        movel(posx(blade_right[1]+5, 0, 0, 0, 0, 0), 20, 10, mod=DR_MV_MOD_REL)
        x1, sol = current_pos = get_current_posx(ref=DR_WORLD)
        
        while (get_modbus_slave(REG_START) == 1 and (x1[0]*-1 < blade_left[1]) and get_modbus_slave(REG_COMMAND) == CMD_READ_DETECTION) :
        #while(1):
            tp_log("Start command received")
            val_x = get_modbus_slave(REG_DETECTION_X)/10
            val_y = get_modbus_slave(REG_DETECTION_Y)/10
            depth = get_modbus_slave(REG_DEPTH)/10
            tp_log("Binary Move Received: X={0}, Y={1}".format(val_x, val_y))
            
            # Execute Relative Move (based on X/Y inputs)
            # We assume these are offsets in mm
            #
            delta_x = [val_x, 0, 0, 0, 0, 0]
            delta_y = [0, val_y+depth, 0, 0, 0, 0]
            delta_neg_y = [0, -(val_y+depth), 0, 0, 0, 0]
            delta_up =  [0, 0, 20, 0, 0, 0]
            delta_down =  [0, 0, -10, 0, 0, 0]
            
            movel(posx(delta_x), vel=300, acc=100,mod=DR_MV_MOD_REL)
            movel(posx(delta_down), vel=400, acc=200,mod=DR_MV_MOD_REL)
            movel(posx(delta_down), vel=400, acc=200,mod=DR_MV_MOD_REL)
            movel(posx(delta_y), vel=300, acc=100,mod=DR_MV_MOD_REL)
            movel(posx(delta_up), vel=400, acc=200,mod=DR_MV_MOD_REL)
            movel(posx(delta_neg_y), vel=400, acc=200,mod=DR_MV_MOD_REL)
            
            wait(3)
            x1, sol = current_pos = get_current_posx(ref=DR_WORLD)
        #movel(System_grinder_app, 20, 20)
        #movel(System_grinder_top, 20, 20)
        #movel(IR_sensor, 50, 20)
        #movel(System_blades_top, 100, 20)
        #movel(System_blade1_new, 20, 20)
        #
        #set_ref_coord(DR_TOOL)
        #
        #movel(posx(0, 0, 11, 0, 0, 0), v=50, a=100)
        #movel(posx(0, 9, 0, 0, 0, 0), v=10, a=10)
        #movel(posx(0, 0, 1, 0, 0, 0), v=10, a=10)
        #set_analog_output(ch=1, val=0)
        #movel(posx(0, 0, -11, 0, 0, 0), v=50, a=100)
        #movel(posx(0, -9, 0, 0, 0, 0), v=10, a=10)
        #
        #
        #set_ref_coord(DR_BASE)
        #
        #movel(System_blades_top, 20, 20)
        continue # Skip the rest of the loop