set_mode_analog_output(ch=1, mod=DR_ANALOG_VOLTAGE)
set_analog_output(ch=1, val=0)

#
movel(System_blade1_new, vel=50, acc=100)
set_ref_coord(DR_TOOL)

move_val = 10
movel(posx(0, 0, 13.3, 0, 0, 0), vel=50, acc=100)
movel(posx(10, 10, 0, 0, 0, 0), vel=50, acc=100)

set_analog_output(ch=1, val=3.2)

movel(posx(-10, -10, 0, 0, 0, 0), vel=50, acc=100)
movel(posx(0, 0, -13.3, 0, 0, 0), vel=50, acc=100)

set_ref_coord(DR_BASE)

movel(System_blade1_new, vel=50, acc=100)

wait(3)

set_ref_coord(DR_TOOL)


movel(posx(0, 0, 13.3, 0, 0, 0), vel=50, acc=100)
movel(posx(10, 10, 0, 0, 0, 0), vel=50, acc=100)

set_analog_output(ch=1, val=0)

movel(posx(-10, -10, 0, 0, 0, 0), vel=50, acc=100)
movel(posx(0, 0, -13.3, 0, 0, 0), vel=50, acc=100)

set_ref_coord(DR_BASE)

movel(System_blade1_new, vel=50, acc=100)

#movel(System_grinder_app, 100,20)
##movel(System_grinder_top, 100, 20)
#movel(System_grinder_invert, 20, 20)
#movel(System_grinder_app, 20,20)
#movel(System_grinder_top, 20, 20)
#
#movel(System_init, 100, 20)

#grinder_angle = System_grinder_invert
#tp_log(str(grinder_angle))
#shift_b = [0,0,0,0,30,0]
#q2 = addto(System_grinder_invert, [0, 0, 0, 0, 30, 0])
##movej (q2, v=10, a=20)
#
#tp_log(str(q2))
#set_ref_coord(DR_WORLD)
#
#posx1 = [100, 20, 300, 90, 0, 180]
#posx2 = [0, 0, 0, 0.1, 30, 0.1]
#add_posx = add_pose(posx1, posx2)
#
#new = posx(System_grinder_invert)
#new[4] = System_grinder_invert[4] + 30
#tp_log(str(new))
#
#movel(new, 20, 20)


#movel(new, 20, 20)

#movel(posx([0,0,0, 5, 0, 0]), 20, 20, ref=DR_BASE, mod=DR_MV_MOD_REL)
##movel(IR_sensor, 100,20)

#movel(System_init, 100, 20)
#movel(IR_sensor, 50, 20)
#
#set_digital_output(1, ON)
#wait(1)
#amovel(posx(0,500,0,0,0,0), vel=30, acc=10,mod=DR_MV_MOD_REL)
#while (get_digital_input(1) == 0):
    #wait(0.01)
#stop(DR_SSTOP)
#
#blade_left, sol = get_current_posx(ref=DR_WORLD)
#
#movel(posx(0,-30,0,0,0,0), vel=40, acc=10,mod=DR_MV_MOD_REL)
#
#amovel(posx(0,-400,0,0,0,0), vel=30, acc=10,mod=DR_MV_MOD_REL)
#
#while (get_digital_input(1) == 0):
    #wait(0.01)