#set_mode_analog_output(ch=1, mod=DR_ANALOG_VOLTAGE)
#set_analog_output(ch=1, val=3.2)
#
#
#movel(System_blade1_new, vel=50, acc=100)
#set_ref_coord(DR_TOOL)
#
#
#movel(posx(0, 0, 13.3, 0, 0, 0), vel=50, acc=100)
#movel(posx(3.5, 3.5, 0, 0, 0, 0), vel=50, acc=100)
#
#set_analog_output(ch=1, val=0)
#
#movel(posx(-3.5, -3.5, 0, 0, 0, 0), vel=50, acc=100)
#movel(posx(0, 0, -13.3, 0, 0, 0), vel=50, acc=100)

#movel(System_grinder_app, 100,20)
#movel(System_grinder_top, 100, 20)
#movel(System_init, 100, 20)
#movel(IR_sensor, 100,20)

movel(System_init, 100, 20)
movel(IR_sensor, 50, 20)

set_digital_output(1, ON)
wait(1)
amovel(posx(0,500,0,0,0,0), vel=30, acc=10,mod=DR_MV_MOD_REL)
while (get_digital_input(1) == 0):
    wait(0.01)
stop(DR_SSTOP)

blade_left, sol = get_current_posx(ref=DR_WORLD)

movel(posx(0,-30,0,0,0,0), vel=40, acc=10,mod=DR_MV_MOD_REL)

amovel(posx(0,-400,0,0,0,0), vel=30, acc=10,mod=DR_MV_MOD_REL)

while (get_digital_input(1) == 0):
    wait(0.01)