#movel(System_grinder_app, 20, 20)
#movel(System_blade1_new, 20, 20)
#set_ref_coord(DR_TOOL)
#
#movel(posx(0, 0, 11, 0, 0, 0), v=50, a=100)
#movel(posx(0, 9, 0, 0, 0, 0), v=10, a=10)
#movel(posx(0, 0, 1, 0, 0, 0), v=10, a=10)
#movel(posx(0, -9, 0, 0, 0, 0), v=10, a=10)
#movel(posx(0, 0, -11, 0, 0, 0), v=50, a=100)
#
#set_ref_coord(DR_BASE)
#
#movel(System_blades_top, 20, 20)

# DRL (Doosan) - EtherNet/IP GPR command consumer

#set_digital_output(1, ON)
#set_analog_output(ch=1, val=3)
# Modbus Register Addresses
REG_BAY_ID = 128
REG_GRINDER_ID = 129
REG_ANGLE = 130
REG_DEPTH = 131
REG_LENGTH = 132
REG_CONFIG_VERSION = 133

REG_DETECTION_X = 134
REG_DETECTION_Y = 135
REG_STATUS = 136
REG_START = 138 
REG_COMMAND = 137

# Command codes
CMD_READ_DETECTION = 11
CMD_RESET = 22

while(1):
    value_x = get_modbus_slave(134)
    value_y = get_modbus_slave(135)
    angle = get_modbus_slave(130)
    stats = get_modbus_slave(REG_START)
    sp =  get_modbus_slave(REG_COMMAND) == CMD_READ_DETECTION

    tp_log("Binary Move Received: X={0}, Y={1}, T={2}, stat ={3}, stop = {4}".format(value_x/10, (65536 - value_y)/10,angle/10, stats, sp))
    
    wait(1)